// lib/bd-locations.ts
export const bdLocations = {
  divisions: [
    {
      name: "Dhaka",
      name_bn: "ঢাকা",
      districts: [
        {
          name: "Dhaka",
          name_bn: "ঢাকা",
          upazilas: [
            { name: "Dhanmondi", name_bn: "ধানমন্ডি" },
            { name: "Gulshan", name_bn: "গুলশান" },
            { name: "Mohammadpur", name_bn: "মোহাম্মদপুর" },
            { name: "Mirpur", name_bn: "মিরপুর" },
            { name: "Uttara", name_bn: "উত্তরা" },
            { name: "Savar", name_bn: "সাভার" },
            { name: "Dhamrai", name_bn: "ধামরাই" },
            { name: "Keraniganj", name_bn: "কেরানীগঞ্জ" },
            { name: "Nawabganj", name_bn: "নবাবগঞ্জ" },
            { name: "Dohar", name_bn: "দোহার" },
          ],
        },
        {
          name: "Gazipur",
          name_bn: "গাজীপুর",
          upazilas: [
            { name: "Kaliakair", name_bn: "কালিয়াকৈর" },
            { name: "Gazipur Sadar", name_bn: "গাজীপুর সদর" },
            { name: "Sreepur", name_bn: "শ্রীপুর" },
            { name: "Kapasia", name_bn: "কাপাসিয়া" },
            { name: "Kaliganj", name_bn: "কালীগঞ্জ" },
          ],
        },
        {
          name: "Narayanganj",
          name_bn: "নারায়ণগঞ্জ",
          upazilas: [
            { name: "Narayanganj Sadar", name_bn: "নারায়ণগঞ্জ সদর" },
            { name: "Sonargaon", name_bn: "সোনারগাঁও" },
            { name: "Bandar", name_bn: "বন্দর" },
            { name: "Araihazar", name_bn: "আড়াইহাজার" },
            { name: "Rupganj", name_bn: "রূপগঞ্জ" },
          ],
        },
        {
          name: "Tangail",
          name_bn: "টাঙ্গাইল",
          upazilas: [
            { name: "Tangail Sadar", name_bn: "টাঙ্গাইল সদর" },
            { name: "Kalihati", name_bn: "কালিহাতী" },
            { name: "Sakhipur", name_bn: "সখিপুর" },
            { name: "Basail", name_bn: "বাসাইল" },
            { name: "Madhupur", name_bn: "মধুপুর" },
            { name: "Ghatail", name_bn: "ঘাটাইল" },
            { name: "Mirzapur", name_bn: "মির্জাপুর" },
          ],
        },
        {
          name: "Kishoreganj",
          name_bn: "কিশোরগঞ্জ",
          upazilas: [
            { name: "Kishoreganj Sadar", name_bn: "কিশোরগঞ্জ সদর" },
            { name: "Bajitpur", name_bn: "বাজিতপুর" },
            { name: "Kuliarchar", name_bn: "কুলিয়ারচর" },
            { name: "Karimganj", name_bn: "করিমগঞ্জ" },
            { name: "Pakundia", name_bn: "পাকুন্দিয়া" },
          ],
        },
        {
          name: "Manikganj",
          name_bn: "মানিকগঞ্জ",
          upazilas: [
            { name: "Manikganj Sadar", name_bn: "মানিকগঞ্জ সদর" },
            { name: "Saturia", name_bn: "সাটুরিয়া" },
            { name: "Shibalaya", name_bn: "শিবালয়" },
            { name: "Harirampur", name_bn: "হরিরামপুর" },
          ],
        },
        {
          name: "Munshiganj",
          name_bn: "মুন্সিগঞ্জ",
          upazilas: [
            { name: "Munshiganj Sadar", name_bn: "মুন্সিগঞ্জ সদর" },
            { name: "Sirajdikhan", name_bn: "সিরাজদিখান" },
            { name: "Lohajang", name_bn: "লৌহজং" },
            { name: "Tongibari", name_bn: "টংগীবাড়ি" },
          ],
        },
        {
          name: "Narsingdi",
          name_bn: "নরসিংদী",
          upazilas: [
            { name: "Narsingdi Sadar", name_bn: "নরসিংদী সদর" },
            { name: "Belabo", name_bn: "বেলাবো" },
            { name: "Monohardi", name_bn: "মনোহরদী" },
            { name: "Shibpur", name_bn: "শিবপুর" },
          ],
        },
        {
          name: "Faridpur",
          name_bn: "ফরিদপুর",
          upazilas: [
            { name: "Faridpur Sadar", name_bn: "ফরিদপুর সদর" },
            { name: "Boalmari", name_bn: "বোয়ালমারী" },
            { name: "Alfadanga", name_bn: "আলফাডাঙ্গা" },
            { name: "Bhanga", name_bn: "ভাঙ্গা" },
          ],
        },
        {
          name: "Gopalganj",
          name_bn: "গোপালগঞ্জ",
          upazilas: [
            { name: "Gopalganj Sadar", name_bn: "গোপালগঞ্জ সদর" },
            { name: "Kashiani", name_bn: "কাশিয়ানি" },
            { name: "Tungipara", name_bn: "টুংগীপাড়া" },
          ],
        },
        {
          name: "Madaripur",
          name_bn: "মাদারীপুর",
          upazilas: [
            { name: "Madaripur Sadar", name_bn: "মাদারীপুর সদর" },
            { name: "Shibchar", name_bn: "শিবচর" },
            { name: "Kalkini", name_bn: "কালকিনি" },
          ],
        },
        {
          name: "Rajbari",
          name_bn: "রাজবাড়ী",
          upazilas: [
            { name: "Rajbari Sadar", name_bn: "রাজবাড়ী সদর" },
            { name: "Goalanda", name_bn: "গোয়ালন্দ" },
            { name: "Pangsha", name_bn: "পাংশা" },
          ],
        },
        {
          name: "Shariatpur",
          name_bn: "শরীয়তপুর",
          upazilas: [
            { name: "Shariatpur Sadar", name_bn: "শরীয়তপুর সদর" },
            { name: "Naria", name_bn: "নড়িয়া" },
            { name: "Zajira", name_bn: "জাজিরা" },
          ],
        },
      ],
    },
    {
      name: "Chittagong",
      name_bn: "চট্টগ্রাম",
      districts: [
        {
          name: "Chittagong",
          name_bn: "চট্টগ্রাম",
          upazilas: [
            { name: "Pahartali", name_bn: "পাহাড়তলী" },
            { name: "Double Mooring", name_bn: "ডাবল মুরিং" },
            { name: "Kotwali", name_bn: "কোতয়ালী" },
            { name: "Bandar", name_bn: "বন্দর" },
            { name: "Patenga", name_bn: "পতেঙ্গা" },
            { name: "Khulshi", name_bn: "খুলশী" },
            { name: "Halishahar", name_bn: "হালিশহর" },
            { name: "Bayejid", name_bn: "বায়েজিদ" },
            { name: "Agrabad", name_bn: "আগ্রাবাদ" },
            { name: "Panchlaish", name_bn: "পাঁচলাইশ" },
          ],
        },
        {
          name: "Cox's Bazar",
          name_bn: "কক্সবাজার",
          upazilas: [
            { name: "Cox's Bazar Sadar", name_bn: "কক্সবাজার সদর" },
            { name: "Teknaf", name_bn: "টেকনাফ" },
            { name: "Ukhiya", name_bn: "উখিয়া" },
            { name: "Ramu", name_bn: "রামু" },
            { name: "Moheshkhali", name_bn: "মহেশখালী" },
          ],
        },
        {
          name: "Comilla",
          name_bn: "কুমিল্লা",
          upazilas: [
            { name: "Comilla Sadar", name_bn: "কুমিল্লা সদর" },
            { name: "Chauddagram", name_bn: "চৌদ্দগ্রাম" },
            { name: "Barura", name_bn: "বরুড়া" },
            { name: "Brahmanpara", name_bn: "ব্রাহ্মণপাড়া" },
            { name: "Burichang", name_bn: "বুড়িচং" },
          ],
        },
        {
          name: "Feni",
          name_bn: "ফেনী",
          upazilas: [
            { name: "Feni Sadar", name_bn: "ফেনী সদর" },
            { name: "Chhagalnaiya", name_bn: "ছাগলনাইয়া" },
            { name: "Sonagazi", name_bn: "সোনাগাজী" },
            { name: "Daganbhuiyan", name_bn: "দাগনভূঞা" },
          ],
        },
        {
          name: "Noakhali",
          name_bn: "নোয়াখালী",
          upazilas: [
            { name: "Noakhali Sadar", name_bn: "নোয়াখালী সদর" },
            { name: "Begumganj", name_bn: "বেগমগঞ্জ" },
            { name: "Chatkhil", name_bn: "চাটখিল" },
            { name: "Senbagh", name_bn: "সেনবাগ" },
          ],
        },
        {
          name: "Chandpur",
          name_bn: "চাঁদপুর",
          upazilas: [
            { name: "Chandpur Sadar", name_bn: "চাঁদপুর সদর" },
            { name: "Hajiganj", name_bn: "হাজীগঞ্জ" },
            { name: "Faridganj", name_bn: "ফরিদগঞ্জ" },
            { name: "Kachua", name_bn: "কচুয়া" },
          ],
        },
        {
          name: "Lakshmipur",
          name_bn: "লক্ষ্মীপুর",
          upazilas: [
            { name: "Lakshmipur Sadar", name_bn: "লক্ষ্মীপুর সদর" },
            { name: "Raipur", name_bn: "রায়পুর" },
            { name: "Ramganj", name_bn: "রামগঞ্জ" },
            { name: "Ramgati", name_bn: "রামগতি" },
          ],
        },
        {
          name: "Brahmanbaria",
          name_bn: "ব্রাহ্মণবাড়িয়া",
          upazilas: [
            { name: "Brahmanbaria Sadar", name_bn: "ব্রাহ্মণবাড়িয়া সদর" },
            { name: "Ashuganj", name_bn: "আশুগঞ্জ" },
            { name: "Nasirnagar", name_bn: "নাসিরনগর" },
            { name: "Sarail", name_bn: "সরাইল" },
          ],
        },
        {
          name: "Rangamati",
          name_bn: "রাঙ্গামাটি",
          upazilas: [
            { name: "Rangamati Sadar", name_bn: "রাঙ্গামাটি সদর" },
            { name: "Kaptai", name_bn: "কাপ্তাই" },
            { name: "Kawkhali", name_bn: "কাউখালী" },
            { name: "Bagaichhari", name_bn: "বাঘাইছড়ি" },
          ],
        },
        {
          name: "Khagrachhari",
          name_bn: "খাগড়াছড়ি",
          upazilas: [
            { name: "Khagrachhari Sadar", name_bn: "খাগড়াছড়ি সদর" },
            { name: "Dighinala", name_bn: "দিঘীনালা" },
            { name: "Panchhari", name_bn: "পানছড়ি" },
            { name: "Ramgarh", name_bn: "রামগড়" },
          ],
        },
        {
          name: "Bandarban",
          name_bn: "বান্দরবান",
          upazilas: [
            { name: "Bandarban Sadar", name_bn: "বান্দরবান সদর" },
            { name: "Alikadam", name_bn: "আলীকদম" },
            { name: "Naikhongchhari", name_bn: "নাইক্ষ্যংছড়ি" },
            { name: "Rowangchhari", name_bn: "রুমা" },
          ],
        },
      ],
    },
    {
      name: "Sylhet",
      name_bn: "সিলেট",
      districts: [
        {
          name: "Sylhet",
          name_bn: "সিলেট",
          upazilas: [
            { name: "Sylhet Sadar", name_bn: "সিলেট সদর" },
            { name: "Beanibazar", name_bn: "বিয়ানীবাজার" },
            { name: "Bishwanath", name_bn: "বিশ্বনাথ" },
            { name: "Dakshin Surma", name_bn: "দক্ষিণ সুরমা" },
            { name: "Balaganj", name_bn: "বালাগঞ্জ" },
            { name: "Companiganj", name_bn: "কোম্পানীগঞ্জ" },
            { name: "Fenchuganj", name_bn: "ফেঞ্চুগঞ্জ" },
            { name: "Golapganj", name_bn: "গোলাপগঞ্জ" },
            { name: "Gowainghat", name_bn: "গোয়াইনঘাট" },
            { name: "Jaintiapur", name_bn: "জৈন্তাপুর" },
            { name: "Kanaighat", name_bn: "কানাইঘাট" },
            { name: "Zakiganj", name_bn: "জাকিগঞ্জ" },
          ],
        },
        {
          name: "Moulvibazar",
          name_bn: "মৌলভীবাজার",
          upazilas: [
            { name: "Moulvibazar Sadar", name_bn: "মৌলভীবাজার সদর" },
            { name: "Barlekha", name_bn: "বড়লেখা" },
            { name: "Juri", name_bn: "জুড়ী" },
            { name: "Kamalganj", name_bn: "কমলগঞ্জ" },
            { name: "Kulaura", name_bn: "কুলাউড়া" },
            { name: "Rajnagar", name_bn: "রাজনগর" },
            { name: "Sreemangal", name_bn: "শ্রীমঙ্গল" },
          ],
        },
        {
          name: "Habiganj",
          name_bn: "হবিগঞ্জ",
          upazilas: [
            { name: "Habiganj Sadar", name_bn: "হবিগঞ্জ সদর" },
            { name: "Ajmiriganj", name_bn: "আজমিরীগঞ্জ" },
            { name: "Baniachong", name_bn: "বানিয়াচং" },
            { name: "Bahubal", name_bn: "বাহুবল" },
            { name: "Chunarughat", name_bn: "চুনারুঘাট" },
            { name: "Lakhai", name_bn: "লাখাই" },
            { name: "Madhabpur", name_bn: "মাধবপুর" },
            { name: "Nabiganj", name_bn: "নবীগঞ্জ" },
          ],
        },
        {
          name: "Sunamganj",
          name_bn: "সুনামগঞ্জ",
          upazilas: [
            { name: "Sunamganj Sadar", name_bn: "সুনামগঞ্জ সদর" },
            { name: "Bishwamvarpur", name_bn: "বিশ্বম্ভরপুর" },
            { name: "Chhatak", name_bn: "ছাতক" },
            { name: "Derai", name_bn: "দিরাই" },
            { name: "Dharampasha", name_bn: "ধরমপাশা" },
            { name: "Dowarabazar", name_bn: "দোয়ারাবাজার" },
            { name: "Jagannathpur", name_bn: "জগন্নাথপুর" },
            { name: "Jamalganj", name_bn: "জামালগঞ্জ" },
            { name: "Sullah", name_bn: "সুল্লা" },
            { name: "Tahirpur", name_bn: "তাহিরপুর" },
          ],
        },
      ],
    },
    {
      name: "Rajshahi",
      name_bn: "রাজশাহী",
      districts: [
        {
          name: "Rajshahi",
          name_bn: "রাজশাহী",
          upazilas: [
            { name: "Rajshahi Sadar", name_bn: "রাজশাহী সদর" },
            { name: "Bagha", name_bn: "বাঘা" },
            { name: "Bagmara", name_bn: "বাগমারা" },
            { name: "Charghat", name_bn: "চারঘাট" },
            { name: "Durgapur", name_bn: "দুর্গাপুর" },
            { name: "Godagari", name_bn: "গোদাগাড়ী" },
            { name: "Mohanpur", name_bn: "মোহনপুর" },
            { name: "Paba", name_bn: "পবা" },
            { name: "Puthia", name_bn: "পুঠিয়া" },
            { name: "Tanore", name_bn: "তানোর" },
          ],
        },
        {
          name: "Natore",
          name_bn: "নাটোর",
          upazilas: [
            { name: "Natore Sadar", name_bn: "নাটোর সদর" },
            { name: "Singra", name_bn: "সিংড়া" },
            { name: "Baraigram", name_bn: "বড়াইগ্রাম" },
            { name: "Bagatipara", name_bn: "বাগাতিপাড়া" },
            { name: "Lalpur", name_bn: "লালপুর" },
            { name: "Gurudaspur", name_bn: "গুরুদাসপুর" },
          ],
        },
        {
          name: "Naogaon",
          name_bn: "নওগাঁ",
          upazilas: [
            { name: "Naogaon Sadar", name_bn: "নওগাঁ সদর" },
            { name: "Mohadevpur", name_bn: "মহাদেবপুর" },
            { name: "Manda", name_bn: "মান্দা" },
            { name: "Niamatpur", name_bn: "নিয়ামতপুর" },
            { name: "Atrai", name_bn: "আত্রাই" },
            { name: "Raninagar", name_bn: "রাণীনগর" },
            { name: "Patnitala", name_bn: "পত্নীতলা" },
            { name: "Dhamoirhat", name_bn: "ধামইরহাট" },
            { name: "Sapahar", name_bn: "সাপাহার" },
            { name: "Porsha", name_bn: "পোরশা" },
            { name: "Badalgachhi", name_bn: "বদলগাছী" },
          ],
        },
        {
          name: "Chapainawabganj",
          name_bn: "চাঁপাইনবাবগঞ্জ",
          upazilas: [
            { name: "Chapainawabganj Sadar", name_bn: "চাঁপাইনবাবগঞ্জ সদর" },
            { name: "Gomastapur", name_bn: "গোমস্তাপুর" },
            { name: "Nachole", name_bn: "নাচোল" },
            { name: "Bholahat", name_bn: "ভোলাহাট" },
            { name: "Shibganj", name_bn: "শিবগঞ্জ" },
          ],
        },
        {
          name: "Pabna",
          name_bn: "পাবনা",
          upazilas: [
            { name: "Pabna Sadar", name_bn: "পাবনা সদর" },
            { name: "Atgharia", name_bn: "আটঘরিয়া" },
            { name: "Bera", name_bn: "বেড়া" },
            { name: "Bhangura", name_bn: "ভাঙ্গুড়া" },
            { name: "Chatmohar", name_bn: "চাটমোহর" },
            { name: "Faridpur", name_bn: "ফরিদপুর" },
            { name: "Ishwardi", name_bn: "ঈশ্বরদী" },
            { name: "Santhia", name_bn: "সাঁথিয়া" },
            { name: "Sujanagar", name_bn: "সুজানগর" },
          ],
        },
        {
          name: "Sirajganj",
          name_bn: "সিরাজগঞ্জ",
          upazilas: [
            { name: "Sirajganj Sadar", name_bn: "সিরাজগঞ্জ সদর" },
            { name: "Belkuchi", name_bn: "বেলকুচি" },
            { name: "Chauhali", name_bn: "চৌহালি" },
            { name: "Kamarkhanda", name_bn: "কামারখন্দ" },
            { name: "Kazipur", name_bn: "কাজীপুর" },
            { name: "Raiganj", name_bn: "রায়গঞ্জ" },
            { name: "Shahjadpur", name_bn: "শাহজাদপুর" },
            { name: "Tarash", name_bn: "তাড়াশ" },
            { name: "Ullahpara", name_bn: "উল্লাপাড়া" },
          ],
        },
        {
          name: "Bogra",
          name_bn: "বগুড়া",
          upazilas: [
            { name: "Bogra Sadar", name_bn: "বগুড়া সদর" },
            { name: "Adamdighi", name_bn: "আদমদিঘী" },
            { name: "Bogra Cantonment", name_bn: "বগুড়া সেনানিবাস" },
            { name: "Dhunat", name_bn: "ধুনট" },
            { name: "Dhupchanchia", name_bn: "দুপচাচিয়া" },
            { name: "Gabtali", name_bn: "গাবতলী" },
            { name: "Kahaloo", name_bn: "কাহালু" },
            { name: "Nandigram", name_bn: "নন্দিগ্রাম" },
            { name: "Sariakandi", name_bn: "সারিয়াকান্দি" },
            { name: "Shajahanpur", name_bn: "শাজাহানপুর" },
            { name: "Sherpur", name_bn: "শেরপুর" },
            { name: "Shibganj", name_bn: "শিবগঞ্জ" },
            { name: "Sonatola", name_bn: "সোনাতলা" },
          ],
        },
        {
          name: "Joypurhat",
          name_bn: "জয়পুরহাট",
          upazilas: [
            { name: "Joypurhat Sadar", name_bn: "জয়পুরহাট সদর" },
            { name: "Akkelpur", name_bn: "আক্কেলপুর" },
            { name: "Kalai", name_bn: "কালাই" },
            { name: "Khetlal", name_bn: "খেতলাল" },
            { name: "Panchbibi", name_bn: "পাঁচবিবি" },
          ],
        },
      ],
    },
    {
      name: "Khulna",
      name_bn: "খুলনা",
      districts: [
        {
          name: "Khulna",
          name_bn: "খুলনা",
          upazilas: [
            { name: "Khulna Sadar", name_bn: "খুলনা সদর" },
            { name: "Dacope", name_bn: "ডাকোপ" },
            { name: "Batiaghata", name_bn: "বটিয়াঘাটা" },
            { name: "Dumuria", name_bn: "ডুমুরিয়া" },
            { name: "Dighalia", name_bn: "দিঘলিয়া" },
            { name: "Koyra", name_bn: "কয়রা" },
            { name: "Paikgacha", name_bn: "পাইকগাছা" },
            { name: "Phultala", name_bn: "ফুলতলা" },
            { name: "Rupsa", name_bn: "রূপসা" },
            { name: "Terokhada", name_bn: "তেরখাদা" },
          ],
        },
        {
          name: "Bagerhat",
          name_bn: "বাগেরহাট",
          upazilas: [
            { name: "Bagerhat Sadar", name_bn: "বাগেরহাট সদর" },
            { name: "Chitalmari", name_bn: "চিতলমারী" },
            { name: "Fakirhat", name_bn: "ফকিরহাট" },
            { name: "Kachua", name_bn: "কচুয়া" },
            { name: "Mollahat", name_bn: "মোল্লাহাট" },
            { name: "Mongla", name_bn: "মোংলা" },
            { name: "Morrelganj", name_bn: "মোরেলগঞ্জ" },
            { name: "Rampal", name_bn: "রামপাল" },
            { name: "Sarankhola", name_bn: "শরণখোলা" },
          ],
        },
        {
          name: "Satkhira",
          name_bn: "সাতক্ষীরা",
          upazilas: [
            { name: "Satkhira Sadar", name_bn: "সাতক্ষীরা সদর" },
            { name: "Assasuni", name_bn: "আশাশুনি" },
            { name: "Debhata", name_bn: "দেবহাটা" },
            { name: "Kalaroa", name_bn: "কলারোয়া" },
            { name: "Kaliganj", name_bn: "কালীগঞ্জ" },
            { name: "Shyamnagar", name_bn: "শ্যামনগর" },
            { name: "Tala", name_bn: "তালা" },
          ],
        },
        {
          name: "Jessore",
          name_bn: "যশোর",
          upazilas: [
            { name: "Jessore Sadar", name_bn: "যশোর সদর" },
            { name: "Abhaynagar", name_bn: "অভয়নগর" },
            { name: "Bagherpara", name_bn: "বাঘারপাড়া" },
            { name: "Chaugachha", name_bn: "চৌগাছা" },
            { name: "Jhikargacha", name_bn: "ঝিকরগাছা" },
            { name: "Keshabpur", name_bn: "কেশবপুর" },
            { name: "Manirampur", name_bn: "মানিরামপুর" },
            { name: "Sharsha", name_bn: "শার্শা" },
          ],
        },
        {
          name: "Jhenaidah",
          name_bn: "ঝিনাইদহ",
          upazilas: [
            { name: "Jhenaidah Sadar", name_bn: "ঝিনাইদহ সদর" },
            { name: "Harinakunda", name_bn: "হরিণাকুন্ড" },
            { name: "Kaliganj", name_bn: "কালীগঞ্জ" },
            { name: "Kotchandpur", name_bn: "কোটচাঁদপুর" },
            { name: "Maheshpur", name_bn: "মহেশপুর" },
            { name: "Shailkupa", name_bn: "শৈলকুপা" },
          ],
        },
        {
          name: "Narail",
          name_bn: "নড়াইল",
          upazilas: [
            { name: "Narail Sadar", name_bn: "নড়াইল সদর" },
            { name: "Kalia", name_bn: "কালিয়া" },
            { name: "Lohagara", name_bn: "লোহাগড়া" },
          ],
        },
        {
          name: "Magura",
          name_bn: "মাগুরা",
          upazilas: [
            { name: "Magura Sadar", name_bn: "মাগুরা সदর" },
            { name: "Mohammadpur", name_bn: "মোহাম্মদপুর" },
            { name: "Shalikha", name_bn: "শালিখা" },
            { name: "Sreepur", name_bn: "শ্রীপুর" },
          ],
        },
        {
          name: "Kushtia",
          name_bn: "কুষ্টিয়া",
          upazilas: [
            { name: "Kushtia Sadar", name_bn: "কুষ্টিয়া সদর" },
            { name: "Bheramara", name_bn: "ভেড়ামারা" },
            { name: "Daulatpur", name_bn: "দৌলতপুর" },
            { name: "Khoksa", name_bn: "খোকসা" },
            { name: "Kumarkhali", name_bn: "কুমারখালী" },
            { name: "Mirpur", name_bn: "মিরপুর" },
          ],
        },
        {
          name: "Meherpur",
          name_bn: "মেহেরপুর",
          upazilas: [
            { name: "Meherpur Sadar", name_bn: "মেহেরপুর সদর" },
            { name: "Gangni", name_bn: "গাংনী" },
            { name: "Mujibnagar", name_bn: "মুজিবনগর" },
          ],
        },
        {
          name: "Chuadanga",
          name_bn: "চুয়াডাঙ্গা",
          upazilas: [
            { name: "Chuadanga Sadar", name_bn: "চুয়াডাঙ্গা সদর" },
            { name: "Alamdanga", name_bn: "আলমডাঙ্গা" },
            { name: "Damurhuda", name_bn: "দামুড়হুদা" },
            { name: "Jibannagar", name_bn: "জীবননগর" },
          ],
        },
      ],
    },
    {
      name: "Barishal",
      name_bn: "বরিশাল",
      districts: [
        {
          name: "Barishal",
          name_bn: "বরিশাল",
          upazilas: [
            { name: "Barishal Sadar", name_bn: "বরিশাল সদর" },
            { name: "Agailjhara", name_bn: "আগৈলঝারা" },
            { name: "Babuganj", name_bn: "বাবুগঞ্জ" },
            { name: "Bakerganj", name_bn: "বাকেরগঞ্জ" },
            { name: "Banaripara", name_bn: "বানারীপাড়া" },
            { name: "Gaurnadi", name_bn: "গৌরনদী" },
            { name: "Hizla", name_bn: "হিজলা" },
            { name: "Mehendiganj", name_bn: "মেহেন্দিগঞ্জ" },
            { name: "Muladi", name_bn: "মুলাদী" },
            { name: "Wazirpur", name_bn: "ওয়াজিরপুর" },
          ],
        },
        {
          name: "Patuakhali",
          name_bn: "পটুয়াখালী",
          upazilas: [
            { name: "Patuakhali Sadar", name_bn: "পটুয়াখালী সদর" },
            { name: "Bauphal", name_bn: "বাউফল" },
            { name: "Dashmina", name_bn: "দশমিনা" },
            { name: "Galachipa", name_bn: "গলাচিপা" },
            { name: "Kalapara", name_bn: "কালাপারা" },
            { name: "Mirzaganj", name_bn: "মির্জাগঞ্জ" },
            { name: "Rangabali", name_bn: "রাঙ্গাবালী" },
          ],
        },
        {
          name: "Pirojpur",
          name_bn: "পিরোজপুর",
          upazilas: [
            { name: "Pirojpur Sadar", name_bn: "পিরোজপুর সদর" },
            { name: "Bhandaria", name_bn: "ভ্যান্ডারিয়া" },
            { name: "Kawkhali", name_bn: "কাউখালী" },
            { name: "Mathbaria", name_bn: "মাঠবাড়িয়া" },
            { name: "Nazirpur", name_bn: "নাজিরপুর" },
            { name: "Nesarabad", name_bn: "নেসারাবাদ" },
            { name: "Zianagar", name_bn: "জিয়ানগর" },
          ],
        },
        {
          name: "Bhola",
          name_bn: "ভোলা",
          upazilas: [
            { name: "Bhola Sadar", name_bn: "ভোলা সদর" },
            { name: "Burhanuddin", name_bn: "বুরহানউদ্দিন" },
            { name: "Char Fasson", name_bn: "চর ফ্যাশন" },
            { name: "Daulatkhan", name_bn: "দৌলতখান" },
            { name: "Lalmohan", name_bn: "লালমোহন" },
            { name: "Manpura", name_bn: "মনপুরা" },
            { name: "Tazumuddin", name_bn: "তজুমদ্দিন" },
          ],
        },
        {
          name: "Jhalokati",
          name_bn: "ঝালকাঠি",
          upazilas: [
            { name: "Jhalokati Sadar", name_bn: "ঝালকাঠি সদর" },
            { name: "Kathalia", name_bn: "কাঠালিয়া" },
            { name: "Nalchity", name_bn: "নলছিটি" },
            { name: "Rajapur", name_bn: "রাজাপুর" },
          ],
        },
        {
          name: "Barguna",
          name_bn: "বরগুনা",
          upazilas: [
            { name: "Barguna Sadar", name_bn: "বরগুনা সদর" },
            { name: "Amtali", name_bn: "আমতলী" },
            { name: "Bamna", name_bn: "বামনা" },
            { name: "Betagi", name_bn: "বেতাগী" },
            { name: "Patharghata", name_bn: "পাথরঘাটা" },
          ],
        },
      ],
    },
    {
      name: "Rangpur",
      name_bn: "রংপুর",
      districts: [
        {
          name: "Rangpur",
          name_bn: "রংপুর",
          upazilas: [
            { name: "Rangpur Sadar", name_bn: "রংপুর সদর" },
            { name: "Badarganj", name_bn: "বদরগঞ্জ" },
            { name: "Gangachara", name_bn: "গঙ্গাচরা" },
            { name: "Kaunia", name_bn: "কাউনিয়া" },
            { name: "Mithapukur", name_bn: "মিঠাপুকুর" },
            { name: "Pirgachha", name_bn: "পীরগাছা" },
            { name: "Pirganj", name_bn: "পীরগঞ্জ" },
            { name: "Taraganj", name_bn: "তারাগঞ্জ" },
          ],
        },
        {
          name: "Dinajpur",
          name_bn: "দিনাজপুর",
          upazilas: [
            { name: "Dinajpur Sadar", name_bn: "দিনাজপুর সদর" },
            { name: "Birampur", name_bn: "বিরামপুর" },
            { name: "Birganj", name_bn: "বীরগঞ্জ" },
            { name: "Bochaganj", name_bn: "বোচাগঞ্জ" },
            { name: "Chirirbandar", name_bn: "চিরিরবন্দর" },
            { name: "Fulbari", name_bn: "ফুলবাড়ী" },
            { name: "Ghoraghat", name_bn: "ঘোড়াঘাট" },
            { name: "Hakimpur", name_bn: "হাকিমপুর" },
            { name: "Kaharole", name_bn: "কাহারোল" },
            { name: "Khansama", name_bn: "খানসামা" },
            { name: "Nawabganj", name_bn: "নবাবগঞ্জ" },
            { name: "Parbatipur", name_bn: "পার্বতীপুর" },
          ],
        },
        {
          name: "Gaibandha",
          name_bn: "গাইবান্ধা",
          upazilas: [
            { name: "Gaibandha Sadar", name_bn: "গাইবান্ধা সদর" },
            { name: "Fulchhari", name_bn: "ফুলছড়ি" },
            { name: "Gobindaganj", name_bn: "গোবিন্দগঞ্জ" },
            { name: "Palashbari", name_bn: "পলাশবাড়ী" },
            { name: "Sadullapur", name_bn: "সাদুল্লাপুর" },
            { name: "Saghata", name_bn: "সাঘাটা" },
            { name: "Sundarganj", name_bn: "সুন্দরগঞ্জ" },
          ],
        },
        {
          name: "Kurigram",
          name_bn: "কুড়িগ্রাম",
          upazilas: [
            { name: "Kurigram Sadar", name_bn: "কুড়িগ্রাম সদর" },
            { name: "Bhurungamari", name_bn: "ভুরুঙ্গামারী" },
            { name: "Char Rajibpur", name_bn: "চর রাজিবপুর" },
            { name: "Chilmari", name_bn: "চিলমারী" },
            { name: "Phulbari", name_bn: "ফুলবাড়ী" },
            { name: "Nageshwari", name_bn: "নাগেশ্বরী" },
            { name: "Rajarhat", name_bn: "রাজারহাট" },
            { name: "Raomari", name_bn: "রৌমারী" },
            { name: "Ulipur", name_bn: "উলিপুর" },
          ],
        },
        {
          name: "Lalmonirhat",
          name_bn: "লালমনিরহাট",
          upazilas: [
            { name: "Lalmonirhat Sadar", name_bn: "লালমনিরহাট সদর" },
            { name: "Aditmari", name_bn: "আদিতমারী" },
            { name: "Hatibandha", name_bn: "হাতীবান্ধা" },
            { name: "Kaliganj", name_bn: "কালীগঞ্জ" },
            { name: "Patgram", name_bn: "পাটগ্রাম" },
          ],
        },
        {
          name: "Nilphamari",
          name_bn: "নীলফামারী",
          upazilas: [
            { name: "Nilphamari Sadar", name_bn: "নীলফামারী সদর" },
            { name: "Dimla", name_bn: "ডিমলা" },
            { name: "Domar", name_bn: "ডোমার" },
            { name: "Jaldhaka", name_bn: "জলঢাকা" },
            { name: "Kishoreganj", name_bn: "কিশোরগঞ্জ" },
            { name: "Saidpur", name_bn: "সৈয়দপুর" },
          ],
        },
        {
          name: "Panchagarh",
          name_bn: "পঞ্চগড়",
          upazilas: [
            { name: "Panchagarh Sadar", name_bn: "পঞ্চগড় সদর" },
            { name: "Atwari", name_bn: "আটোয়ারী" },
            { name: "Boda", name_bn: "বোদা" },
            { name: "Debiganj", name_bn: "দেবীগঞ্জ" },
            { name: "Tetulia", name_bn: "তেতুলিয়া" },
          ],
        },
        {
          name: "Thakurgaon",
          name_bn: "ঠাকুরগাঁও",
          upazilas: [
            { name: "Thakurgaon Sadar", name_bn: "ঠাকুরগাঁও সদর" },
            { name: "Baliadangi", name_bn: "বালিয়াডাঙ্গী" },
            { name: "Haripur", name_bn: "হরিপুর" },
            { name: "Pirganj", name_bn: "পীরগঞ্জ" },
            { name: "Ranisankail", name_bn: "রাণীশংকৈল" },
          ],
        },
      ],
    },
    {
      name: "Mymensingh",
      name_bn: "ময়মনসিংহ",
      districts: [
        {
          name: "Mymensingh",
          name_bn: "ময়মনসিংহ",
          upazilas: [
            { name: "Mymensingh Sadar", name_bn: "ময়মনসিংহ সদর" },
            { name: "Bhaluka", name_bn: "ভালুকা" },
            { name: "Trishal", name_bn: "ত্রিশাল" },
            { name: "Haluaghat", name_bn: "হালুয়াঘাট" },
            { name: "Muktagachha", name_bn: "মুক্তাগাছা" },
            { name: "Dhobaura", name_bn: "ধোবাউরা" },
            { name: "Fulbaria", name_bn: "ফুলবাড়িয়া" },
            { name: "Gaffargaon", name_bn: "গফরগাঁও" },
            { name: "Gauripur", name_bn: "গৌরীপুর" },
            { name: "Ishwarganj", name_bn: "ঈশ্বরগঞ্জ" },
            { name: "Nandail", name_bn: "নান্দাইল" },
            { name: "Phulpur", name_bn: "ফুলপুর" },
          ],
        },
        {
          name: "Jamalpur",
          name_bn: "জামালপুর",
          upazilas: [
            { name: "Jamalpur Sadar", name_bn: "জামালপুর সদর" },
            { name: "Baksiganj", name_bn: "বকসিগঞ্জ" },
            { name: "Dewanganj", name_bn: "দেওয়ানগঞ্জ" },
            { name: "Islampur", name_bn: "ইসলামপুর" },
            { name: "Madarganj", name_bn: "মাদারগঞ্জ" },
            { name: "Melandaha", name_bn: "মেলান্দহ" },
            { name: "Sarishabari", name_bn: "সরিষাবাড়ী" },
          ],
        },
        {
          name: "Netrokona",
          name_bn: "নেত্রকোণা",
          upazilas: [
            { name: "Netrokona Sadar", name_bn: "নেত্রকোণা সদর" },
            { name: "Atpara", name_bn: "আটপাড়া" },
            { name: "Barhatta", name_bn: "বারহাট্টা" },
            { name: "Durgapur", name_bn: "দুর্গাপুর" },
            { name: "Khaliajuri", name_bn: "খালিয়াজুরী" },
            { name: "Kalmakanda", name_bn: "কলমাকান্দা" },
            { name: "Kendua", name_bn: "কেন্দুয়া" },
            { name: "Madan", name_bn: "মদন" },
            { name: "Mohanganj", name_bn: "মোহনগঞ্জ" },
            { name: "Purbadhala", name_bn: "পূর্বধলা" },
          ],
        },
        {
          name: "Sherpur",
          name_bn: "শেরপুর",
          upazilas: [
            { name: "Sherpur Sadar", name_bn: "শেরপুর সদর" },
            { name: "Jhenaigati", name_bn: "ঝিনাইগাতী" },
            { name: "Nakla", name_bn: "নকলা" },
            { name: "Nalitabari", name_bn: "নালিতাবাড়ী" },
            { name: "Sreebardi", name_bn: "শ্রীবরদী" },
          ],
        },
      ],
    },
  ],
} as const;

// Type inference
export type Division = (typeof bdLocations.divisions)[number];
export type District = Division["districts"][number];
export type Upazilla = District["upazilas"][number];
